Tests
Genry72/gophermart pull request #4
Opened 2023-10-17 06:02 UTC by Genry72

2023-10-17 19:11 UTC, popoffvg requested changes

2023-10-17 19:11 UTC, popoffvg commented on internal/repositories/accrual/accrual.go
> +				result = append(result, accuralStatus)
лучше аллоцировать спайс make([]*models.ResponseAccrual, len(orderIDs)) и тогда можно будет обойтись точно без мьютексов. 

Обращение по индексу в слайде атомарная операция

2023-10-17 19:11 UTC, popoffvg commented on internal/usecases/accrual/accrual.go
> +			cancel()
Контекст будет отменен при отмене родительского контекста и повторно cancel вызывать необязательно

2023-10-17 19:11 UTC, popoffvg commented on internal/usecases/accrual/accrual.go
> +	case <-o.doneCtx.Done():
doneCtx будет отменен сразу же вместе с родительским контекстом, т.к. был создан на основе родительского.

2023-10-17 19:11 UTC, popoffvg commented on internal/repositories/postgre/balances/draw.go
> +INSERT INTO withdraw (user_id, order_id, points, date)
Возможно создание нескольких списаний по одному заказу при || отправке запроса. И баланс пользователя может уйти в минус.

2023-10-17 19:11 UTC, popoffvg commented on internal/repositories/postgre/migrations/0001_tables.up.sql
> +    accrual    double precision        not null,
Не стоит использовать для хранения денежных средств double, float etc. Стоит использовать numeric

2023-10-17 19:11 UTC, popoffvg commented on internal/repositories/accrual/accrual.go
> +					return
Не стоит прерывать обработку при ошибке в одном заказе.

2023-10-17 19:11 UTC, popoffvg commented on internal/repositories/accrual/accrual.go
> +				defer func() {
defer выполнится только после выхода из функции, а не после выполнение запроса

2023-10-17 22:04 UTC, Genry72 commented on internal/usecases/accrual/accrual.go
> +			cancel()
Здесь в первую очередь хотелось дождаться корректного завершения. Сделал donectx, cancel := context.WithCancel(context.Background()) при этом вызов cancel() оставил, чтобы убедиться что select case <-ctx.Done() сработал и закончена вся работа

2023-10-17 22:05 UTC, Genry72 commented on internal/repositories/accrual/accrual.go
> +					return
Здесь цикл не прерывается, это выход из анонимной функции

2023-10-17 22:05 UTC, Genry72 commented on internal/repositories/accrual/accrual.go
> +				defer func() {
Такая задумка и была. Выход после выполнения запроса, обработка статуса и добавления в слайс. Есть причины сделать по другому? Кажется что код усложнится, так как вычитку из канала нужно будет ставить в нескольких местах.

2023-10-24 18:09 UTC, popoffvg commented on internal/repositories/postgre/balances/draw.go
> +		if _, err := tx.ExecContext(ctx, "LOCK TABLE withdraw IN SHARE MODE;"); err != nil {
Так делать не стоит и нужно блокировать счет пользователя или самого пользователя. В этом случае степень || будет выше

2023-10-24 18:09 UTC, popoffvg commented on internal/repositories/postgre/balances/draw.go
> +    orders o
Будет очень дорогая операция при большом кол-ве записей. В учебном проекте допустимо

2023-10-24 18:09 UTC, popoffvg commented on internal/usecases/orders/get_test.go
> +	mockCtl := gomock.NewController(t)
Такие тесты писать не стоит, т.к. проверяешь мок. Реальной логики в методах, на которые написаны тесты нет.

2023-10-26 10:57 UTC, Genry72 commented on internal/usecases/orders/get_test.go
> +	mockCtl := gomock.NewController(t)
Согласен, это больше для coverage

2023-10-30 06:32 UTC, popoffvg approved these changes

2023-10-30 17:04 UTC, merged